version: '3.8'

services:
  autou:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - ZSL_MODEL=${ZSL_MODEL:-joeddav/xlm-roberta-large-xnli}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - MAX_TEXT_CHARS=${MAX_TEXT_CHARS:-20000}
    volumes:
      - ./app:/app/app:ro  # Mount source code for development (optional)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - autou
  #   restart: unless-stopped